-- AlterTable
ALTER TABLE "TagLink" ALTER COLUMN "idAlbum" DROP NOT NULL,
ALTER COLUMN "idArtist" DROP NOT NULL,
ALTER COLUMN "idSong" DROP NOT NULL;

-- AddForeignKey
ALTER TABLE "TagLink" ADD CONSTRAINT "TagLink_idTag_fkey" FOREIGN KEY ("idTag") REFERENCES "Tag"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TagLink" ADD CONSTRAINT "TagLink_idSong_fkey" FOREIGN KEY ("idSong") REFERENCES "Song"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TagLink" ADD CONSTRAINT "TagLink_idAlbum_fkey" FOREIGN KEY ("idAlbum") REFERENCES "Album"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TagLink" ADD CONSTRAINT "TagLink_idArtist_fkey" FOREIGN KEY ("idArtist") REFERENCES "Artist"("id") ON DELETE SET NULL ON UPDATE CASCADE;
